package com.pankajgadge.quiz.domain.usecase

import com.pankajgadge.core.common.result.Result
import com.pankajgadge.core.domain.model.Question
import com.pankajgadge.core.domain.model.QuestionAnswer
import com.pankajgadge.core.domain.model.QuestionType
import com.pankajgadge.core.domain.model.Quiz
import com.pankajgadge.core.domain.model.QuizResult
import com.pankajgadge.core.domain.model.SubmitQuizRequest
import com.pankajgadge.core.domain.model.SubmitQuizResponse
import com.pankajgadge.core.domain.model.SubmittedAnswer
import com.pankajgadge.core.domain.repository.QuizRepository
import com.pankajgadge.core.domain.repository.UserProfileRepository
import com.pankajgadge.quiz.model.QuizResultUiState
import java.lang.Exception
import javax.inject.Inject

/**
 * Use case for submitting a completed quiz
 * Calculates score and saves result
 */
class SubmitQuizUseCase @Inject constructor(
    private val quizRepository: QuizRepository,
    private val userProfileRepository: UserProfileRepository
) {
    suspend operator fun invoke(request: SubmitQuizRequest): Result<SubmitQuizResponse> {
        // Validate request
        if (request.quizId.isBlank()) {
            return Result.Error(Exception("Quiz ID cannot be empty"))
        }
        if (request.userId.isBlank()) {
            return Result.Error(Exception("User ID cannot be empty"))
        }
        if (request.answers.isEmpty()) {
            return Result.Error(Exception("No answers submitted"))
        }

        // Get quiz details
        val quizResult = quizRepository.getQuizById(request.quizId)
        if (quizResult !is Result.Success) {
            return Result.Error(Exception("Failed to load quiz details"))
        }
        val quiz = quizResult.data

        // Calculate score
        val scoreResult = calculateScore(quiz, request.answers)

        // Create quiz result
        val quizResultData = QuizResult(
            id = "", // Will be generated by Firestore
            userId = request.userId,
            quizId = request.quizId,
            quizTitle = quiz.title,
            score = scoreResult.correctAnswers,
            totalQuestions = quiz.questions.size,
            correctAnswers = scoreResult.correctAnswers,
            wrongAnswers = scoreResult.wrongAnswers,
            totalPoints = scoreResult.totalPoints,
            earnedPoints = scoreResult.earnedPoints,
            timeTaken = request.timeTaken,
            completedAt = request.completedAt,
            answers = scoreResult.detailedAnswers
        )

        // Save result to Firestore
        val saveResult = userProfileRepository.saveQuizResult(quizResultData)
        if (saveResult !is Result.Success) {
            return Result.Error(Exception("Failed to save quiz result"))
        }

        // TODO Update quizResultData.id = saveResult.id

        if (quizResult != null) {
            quizResultData.id = saveResult.data.id
        }
//        else {
//            _uiState.value = QuizResultUiState.Error("Quiz result not found")
//        }
        // Create response
        val response = SubmitQuizResponse(
            resultId = quizResultData.id,
            score = scoreResult.correctAnswers,
            totalQuestions = quiz.questions.size,
            correctAnswers = scoreResult.correctAnswers,
            wrongAnswers = scoreResult.wrongAnswers,
            totalPoints = scoreResult.totalPoints,
            earnedPoints = scoreResult.earnedPoints,
            timeTaken = request.timeTaken,
            quizResult = quizResultData
        )

        return Result.Success(response)
    }

    /**
     * Calculate score by comparing user answers with correct answers
     */
    private fun calculateScore(
        quiz: Quiz,
        userAnswers: Map<String, SubmittedAnswer>
    ): ScoreResult {
        var correctAnswers = 0
        var wrongAnswers = 0
        var earnedPoints = 0
        val totalPoints = quiz.questions.sumOf { it.points }
        val detailedAnswers = mutableMapOf<String, QuestionAnswer>()

        quiz.questions.forEach { question ->
            val userAnswer = userAnswers[question.id]

            if (userAnswer != null) {
                val isCorrect = checkAnswer(question, userAnswer.selectedAnswer)

                if (isCorrect) {
                    correctAnswers++
                    earnedPoints += question.points
                } else {
                    wrongAnswers++
                }

                detailedAnswers[question.id] = QuestionAnswer(
                    questionId = question.id,
                    questionType = QuestionType.MULTIPLE_CHOICE, // TODO: Support other types
                    userAnswer = userAnswer.selectedAnswer,
                    correctAnswer = question.correctAnswer.toString(),
                    isCorrect = isCorrect,
                    pointsEarned = if (isCorrect) question.points else 0
                )
            } else {
                wrongAnswers++
                detailedAnswers[question.id] = QuestionAnswer(
                    questionId = question.id,
                    questionType = QuestionType.MULTIPLE_CHOICE,
                    userAnswer = "",
                    correctAnswer = question.correctAnswer.toString(),
                    isCorrect = false,
                    pointsEarned = 0
                )
            }
        }

        return ScoreResult(
            correctAnswers = correctAnswers,
            wrongAnswers = wrongAnswers,
            earnedPoints = earnedPoints,
            totalPoints = totalPoints,
            detailedAnswers = detailedAnswers
        )
    }

    /**
     * Check if user's answer is correct
     */
    private fun checkAnswer(question: Question, userAnswer: String): Boolean {
        return when {
            // Multiple choice - compare index
            userAnswer.toIntOrNull() != null -> {
                userAnswer.toInt() == question.correctAnswer
            }
            // Text answer - exact match (for future fill-in-blank)
            else -> {
                userAnswer.trim().equals(
                    question.options.getOrNull(question.correctAnswer)?.trim(),
                    ignoreCase = true
                )
            }
        }
    }

    /**
     * Internal data class for score calculation
     */
    private data class ScoreResult(
        val correctAnswers: Int,
        val wrongAnswers: Int,
        val earnedPoints: Int,
        val totalPoints: Int,
        val detailedAnswers: Map<String, QuestionAnswer>
    )
}